# Generated by Django 5.0.6 on 2024-05-30 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paramaxApp', '0002_otp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=255)),
                ('category_icon', models.ImageField(blank=True, null=True, upload_to='category-icons/')),
                ('added_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
