# Generated by Django 5.0.6 on 2024-06-08 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paramaxApp', '0004_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='servie_image',
            field=models.ImageField(blank=True, null=True, upload_to='service-images/'),
        ),
    ]
