# Generated by Django 5.0.6 on 2024-06-10 11:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paramaxApp', '0005_services_servie_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, null=True)),
                ('time', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField()),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='paramaxApp.services')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
